j_rs_shop_jrs_product_user:
    resource: "@JRsShopBundle/Resources/config/routing/productUser.yml"
    prefix:   /jrs_product

j_rs_shop_jrs_product:
    resource: "@JRsShopBundle/Resources/config/routing/product.yml"
    prefix:   /admin/jrs_product

j_rs_shop_user:
    resource: "@JRsShopBundle/Resources/config/routing/user.yml"
    prefix:   /users

j_rs_shop_homepage:
    path:     /
    defaults: { _controller: JRsShopBundle:Page:homepage }
    requirements:
                _method:  GET

j_rs_shop_about:
    path:     /about
    defaults: { _controller: JRsShopBundle:Page:about }
    requirements:
            _method:  GET

j_rs_shop_contacts:
    path:     /contacts
    defaults: { _controller: JRsShopBundle:Page:contacts }
    requirements:
            _method:  GET|POST


j_rs_shop_registration:
    path:     /registration
    defaults: { _controller: JRsShopBundle:Registration:form }
    requirements:
      _method:  GET|POST


j_rs_shop_category_show:
    path:     /category/{id}
    defaults: { _controller: JRsShopBundle:Category:index }
    requirements:
      _method:  GET
      id: \d+

j_rs_shop_category:
    path:     /category/{slug}
    defaults: { _controller: JRsShopBundle:Category:index}

j_rs_shop_mail:
    pattern:     /mail
    defaults: { _controller: JRsShopBundle:Page:sendEmailT}
