jrs_product:
    path:     /
    defaults: { _controller: "JRsShopBundle:Product:index" }


jrs_product_show:
    path:     /{id}/show
    defaults: { _controller: "JRsShopBundle:Product:show" }

jrs_product_new:
    path:     /new
    defaults: { _controller: "JRsShopBundle:Product:new" }

jrs_product_create:
    path:     /create
    defaults: { _controller: "JRsShopBundle:Product:create" }
    requirements: { _method: post }

jrs_product_edit:
    path:     /{id}/edit
    defaults: { _controller: "JRsShopBundle:Product:edit" }

jrs_product_update:
    path:     /{id}/update
    defaults: { _controller: "JRsShopBundle:Product:update" }
    requirements: { _method: post|put }

jrs_product_delete:
    path:     /{id}/delete
    defaults: { _controller: "JRsShopBundle:Product:delete" }
    requirements: { _method: post|delete }
